services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=aiquery
      - POSTGRES_USER=aiquery
      - POSTGRES_PASSWORD=aiquery
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiquery -d aiquery"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
